const EMAIL_VERIFICATION_ENABLED = true;

// const PHONE_VERIFICATION_ENABLED = true;
const PHONE_VERIFICATION_ENABLED = false;

module.exports = {
  EMAIL_VERIFICATION_ENABLED,
  PHONE_VERIFICATION_ENABLED,
};
